CREATE TABLE FOOD (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL ,
  cost FLOAT NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE USERS (
  id INT NOT NULL AUTO_INCREMENT,
  username VARCHAR(40) NOT NULL,
  password VARCHAR(40) NOT NULL,
  first_name VARCHAR(40) NOT NULL,
  last_name VARCHAR(40),
  enabled TINYINT NOT NULL DEFAULT 1,
  role VARCHAR(15) NOT NULL DEFAULT 'ROLE_USER',
  phone_number LONG,
  address VARCHAR(250),
  PRIMARY KEY (ID)
);