CREATE TABLE FOOD (
  ID INT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(255) NOT NULL ,
  COST FLOAT NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE USERS (
  ID INT NOT NULL AUTO_INCREMENT,
  USERNAME VARCHAR(40) NOT NULL,
  PASSWORD VARCHAR(40) NOT NULL,
  ENABLED TINYINT NOT NULL DEFAULT 1,
  ROLE VARCHAR(15) DEFAULT 'ROLE_USER',
  PHONE_NUMBER LONG,
  ADDRESS VARCHAR(250),
  PRIMARY KEY (ID)
);