INSERT INTO food (NAME, COST) VALUES ('Potato', 1.25);
INSERT INTO food (NAME, COST) VALUES ('Pigeon', 10.00);
INSERT INTO users (USERNAME, PASSWORD, PHONE_NUMBER, ADDRESS) VALUES ('ilya', '123', 123456789, 'Moscow Red Square');